from wx.lib.embeddedimage import PyEmbeddedImage

cross=PyEmbeddedImage(
"AAABAAEADAwAAAAAAADoBAAAFgAAACgAAAAMAAAAGAAAAAEACAAAAAAAwAAAAAAAAAAAAAAAAAAA"
"AAAAAAAAAAAAAACAAACAAAAAgIAAgAAAAIAAgACAgAAAwMDAAICAgAAAAP8AAP8AAAD//wD/AAAA"
"/wD/AP//AAD///8AwwAAAM8AAADbAAAA5wAAAPMAAAD/AAAA/xcXAP8vLwD/U1MA/2tnAP9/fwD/"
"i4sA/5eXAP+jowD/r68A/7u7AP/HxwD/z8cA/9vbAP/n5wD/8/MA//v3ACsrUwA3N18AQ0NrAE9P"
"dwBXV38AY2OLAG9vlwB/f6cAi4uzAJeXvwCnp88As7PbAL+/5wDHx+8Az8/3AFMrKwBfNzcAa0ND"
"AHdPTwCDW1sAj2dnAJtzcwCnf38As4uLAL+XlwDLo6MA16+vAOO7uwDrw8MA+9PTAC9TLwA7XzsA"
"R2tHAFN3UwBfg18Aa49rAHebdwCDp4MAj7OPAJu/mwCny6cAs9ezAL/jvwDL78sA1/vXAIdvlwCX"
"f6cAp4+3ALObwwDDq9MAz7ffANvD6wCLl28Ak6N7AJ+vhwCru5MAt8efAMvbswDX578A4/PLAAtv"
"mwAPe6MAE4evABePtwAbm8MAF6fPABuz2wAjv+cAK8vzADfX/wD/8/8A/+v/AP/f/wD/0/8A/8f/"
"AP+3/wD/o/8A/5f/AP+D/wD/a/8A/0v/AOcA5wDXANcAwwDHALcAtwCjAKcAlwCXAIsAiwB3AHcA"
"ZwBnAE8AUwAvADMA6///AOf//wDf//8A0///ALv//wCb//8AP///AADz9wAA5+sAAN/fAADT0wAA"
"x8cAALu7AACzrwAAp6cAAJuXAACXjwAAf38AAHd3AABfXwAAR0cAADMzAP//9wD//+cA///bAP//"
"xwD//7sA//+XAP//fwD//1MA7+8AAOPjAADX1wAAy8sAAL+/AACzswAAo6MAAJeTAACLgwAAe3sA"
"AGdrAABbWwAAR0sAACMjAADz//MA3//nANf/1wDD/88Au/+7AKP/owCH/4cAZ/9nADf/NwAL/wAA"
"APMAAADrAAAA4wAAANcAAADLAAAAvwAAALMAAACnAAAAnwAAAJMAAACHAAAAfwAAAHcAAABvAAAA"
"ZwAAAF8AAABTAAAARwAAADcAAAAjAAD38/8A6+v/AN/f/wDT0/8Aw8P/AK+v/wCbm/8Ai4v/AHd3"
"/wBnZ/8AU1P/AEND/wAvL/8AFxf/AAAARwAAAFcAAABnAAAAcwAAAH8AAACLAAAAlwAAAKMAAACv"
"AAAAuwAAAMMAAADPAAAA2wAAAOcAAADzAHwAVACbAGkAugB+ANkAkwDwAKoA/yS2AP9IwgD/bM4A"
"/5DaAP+05gDw8PAA3NzcAMjIyAC0tLQAoKCgAICAgAAAAP8AAP8AAAD//wD/AAAA/wD/AP//AAD/"
"//8ATklHR0dHR0dHR0dHUEtKSUlJSUlJSUhJUE29v7+/v7+/v0lJUE28vb0PD7+/v0pKUE28vL0P"
"D72/v0pKUE62Dw8PDw8Pv0pKUE62Dw8PDw8PvUpKUE62trYPD7y9vUpKUE62trYPD7y8vUpKULO2"
"tra2tra2vEtKUVCzs7Ozs7OzTk1N81FRUVFRUVFRUVFRAA///wAP//8AD///AA///wAP//8AD///"
"AA///wAP//8AD///AA///wAP//8AD///")
origin=PyEmbeddedImage(
"AAABAAEADQ0AAAAAAAAsBQAAFgAAACgAAAANAAAAGgAAAAEACAAAAAAABAEAAAAAAAAAAAAAAAAA"
"AAAAAAAAAAAAgICAAMDAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/"
"//8AAAAAAAAAAgAAAAAAAAAAAAAAAAAAAgICAAAAAAAAAAAAAAACAgAAAAICAAAAAAAAAAACAAAA"
"AAAAAAIAAAAAAAAAAgAAAAAAAAACAAAAAAAAAgAAAAAAAAAAAAIAAAAAAAIAAAAAAAAAAAACAAAA"
"AAACAAAAAAAAAAAAAgAAAAAAAAIAAAAAAAAAAgAAAAAAAAACAAAAAAAAAAIAAAAAAAAAAAICAAAA"
"AgIAAAAAAAAAAAAAAAICAgAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAP3////4////5z///9/f///d"
"3///ve///7Bv//+97///3d///9/f///nP///+P////3///8=")
point = PyEmbeddedImage(
    "AAABAAEADQ0AAAAAAABkAgAAFgAAACgAAAANAAAAGgAAAAEAGAAAAAAAPAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACuk3KJXy1/UBuJXy2uk3IAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf1EcrZBu1sm69vXz2cu8r5Fwf1EcAAAAAAAAAAAAAAAAAAAAAKKBXNLFtvb39/j5+fn6+vv8/P39/dnMvKaFYAAAAAAAAAAAAAB/URzPw7Px8/Pz9fX29/f4+fn5+vr7/Pz9/f3ZzLx/URwAAAAAr5Nzp4tp7O/v7/Hx5u7omMyaJJYkl8mY7fPu+/z8/f39r5Fwr5NzAIleLsi+runs7Ozv757SoCeoKiCiIhCSE5fImPn6+vv8/NnLvIleLgB/UBvf4d/m6urp7OxKv00/w0I1uTghoSEjlib4+fn5+vr29fN/UBsAiV4uxbqr4+fn5urqptypUdVVP8NDJqgpmMya9vf3+Pn51sm6iV4uAK+Tc6OHZuHl5ePn597o4qbcqUq/TZ7SoObu6PP19fb3962Qbq+TcwAAAAB/URzDuanh5eXj5+fm6urp7Ozs7+/v8fHx8/PSxbZ/URwAAAAAAAAAAAAAnHxXw7mp4eXl4+fn5urq6ezs7O/vz8OzooFcAAAAAAAAAAAAAAAAAAAAAH9RHKOHZsW6q9/h38i+rqeLaX9RHAAAAAAAAAAAAAAAAAAAAAAAAAAAAACvk3OJXy5/UBuJXy6vk3MAAAAAAAAAAAAAAAAA8H///+A////AH///gA///wAH//8AB///AAf//wAH//8AB///gA///8Af///gP///8H///w=="
)
if __name__=='__main__':
    import base64
    imgfile = 'haiqinyan_wlop.jpg'
    d=open(imgfile,'rb').read()
    d = base64.b64encode(d).decode('utf8')
    open('est.txt','w').write('"{}"'.format(d))